# -*- coding: utf-8 -*-
"""Exp2_SMA_scraping.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Tn2VTcwCnutMqpkKDOjvIS_0GMztCX5h

**Part 1- Scraping Youtube Video Comments**

**Use** **API_key**
"""

import requests

video_id = "R3GfuzLMPkA"

api_key = "AIzaSyBrINsyS8g5121cG6SqCwKf8bc_DPlUm3E"

"""**Retrieve video** **information**"""

# Retrieve video information
video_info_url = f"https://www.googleapis.com/youtube/v3/videos?part=snippet&id={video_id}&key={api_key}"
video_info_response = requests.get(video_info_url)
video_info_data = video_info_response.json()

video_info_data

"""**Retrieve video comment**s"""

# Retrieve video compnts
comments_url = f"https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId={video_id}&key={api_key}"
comments_response= requests.get(comments_url)
comments_data = comments_response.json()

comments_data

"""**Extract the comments**"""

# Extract the comments
comments = [item["snippet"]["topLevelComment"]["snippet"]["textOriginal"] for item in comments_data["items"]]

print(comments)

import pandas as pd

display = pd.DataFrame({"Comments": comments})

display.head()

"""**Save Comments to CSV File**"""

display.to_csv("YouTube_Comments_Sentiment.csv")

"""**Sentiments Analysis of Youtube Comments**"""

from textblob import TextBlob

def get_comment_sentiment(comment):
  analysis = TextBlob(comment)
  if analysis.sentiment.polarity > 0:
    return "Positive"
  elif analysis.sentiment.polarity == 0:
    return "neutral"
  else:
    return "negative"

"""**Display the sentiment of Youtube video comments**"""

comment_list = []
sentiment_list = []
for comment in comments:
  sentiment = get_comment_sentiment(comment)
  comment_list.append(comment)
  sentiment_list.append(sentiment)
  print(f"{comment} : {sentiment}")

import pandas as pd

sentiment_df = pd.DataFrame({"Comments": comment_list,"Sentiment": sentiment_list})

sentiment_df.head()

"""**Save Comments to CSV File**"""

sentiment_df.to_csv("YouTube_Comments_Sentiment.csv")

